name: Generate index.json

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate index.json
        run: |
          echo "{" > index.json
          first_dir=true

          for dir in */ ; do
            dirname=$(basename "$dir")

            # skip .github
            if [[ "$dirname" == ".github" ]]; then
              continue
            fi

            if [ "$first_dir" = true ]; then
              first_dir=false
            else
              echo "," >> index.json
            fi

            echo -n "  \"$dirname\": [" >> index.json

            first_file=true
            for file in "$dir"*; do
              if [[ -f "$file" && "$file" =~ \.(png|svg|jpg)$ ]]; then
                filename=$(basename "$file")

                if [ "$first_file" = true ]; then
                  first_file=false
                else
                  echo -n "," >> index.json
                fi

                echo -n "\"$filename\"" >> index.json
              fi
            done

            echo -n "]" >> index.json
          done

          echo "" >> index.json
          echo "}" >> index.json

      - name: Commit index.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.json
          git commit -m "Auto update index.json" || echo "No changes"
          git push
